services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935" # Nginx rtmp - hls
      - "8080:8080" # Nginx Web
    volumes:
      - ./data:/tmp/hls

  server:
    build: ./server
    ports:
      - "3000:3000"
    container_name: backend_server
